mirrors:
  # Example configurations for different types of images
  - source: "docker.io/bitnami/postgresql"
    destination: "ghcr.io/{{GITHUB_REPOSITORY_OWNER}}/bitnami/postgresql"
    tags:
      - "17.5.0-debian-12-r3"
  - source: "docker.io/kong/kubernetes-ingress-controller"
    destination: "ghcr.io/{{GITHUB_REPOSITORY_OWNER}}/kubernetes-ingress-controller"
    tags:
      - "3.4"
  - source: "docker.io/kong"
    destination: "ghcr.io/{{GITHUB_REPOSITORY_OWNER}}/kong"
    tags:
      - "3.9"


# Global settings
settings:
  # Whether to make mirrored images public (true) or private (false)
  public: true
  
  # Whether to preserve original labels and annotations
  preserve_metadata: true
  
  # Retry configuration
  retry_attempts: 3
  retry_delay: 30  # seconds
  
  # Parallel processing
  max_concurrent_mirrors: 5 
